### ISSUE TITLE
Uniformed Documentation Structure

### ISSUE THREAD

**Issue by devnote-dev** [devnote-dev/ptero-notes#21]
Currently different parts of documentation for the different APIs seem to be having their own variations of markdown formatting. This doesn't really help with consistency, especially when cross-referencing different APIs. It would be good to have a `CONTRIBUTING.md` file stating the formatting rules along with some other useful information for contributing.

It might also help to have markdown linting, perhaps as part of CI?

**Comment by DEV-DIBSTER** [comment]
One variation in markdown I have noticed is [Application README.md](https://github.com/devnote-dev/ptero-notes/blob/main/pterodactyl/application/README.md) and [Client README.md](https://github.com/devnote-dev/ptero-notes/blob/main/pterodactyl/client/README.md) which both have different sized Access headers. I assume this is what you're referring to?

**Comment by devnote-dev** [comment]
Yes, that's part of it. Other endpoints for the application API also make use of the old table structure for representing field keys in data structures such as request parameters and request body, and not all endpoints with varying response bodies have example response models available. The Wings API is the most up-to-date and has the most coverage, making use of the new table structure for data structures, consistent headings and even source links. Ideally a similar format to this would be applied to the documentation for all APIs.

**Comment by DEV-DIBSTER** [comment]
I do agree that there should be some sort of uniformity between these. Potentially finishing the API documentation so we have a fully documented Pterodactyl API, and then decided and finalizing formatting after all the endpoints have been documented? I think that would be the easiest.

**Comment by devnote-dev** [comment]
This was my initial thought process, but that would mean that we would have to rewrite all the files to the new format once the documentation for all the APIs are complete. Currently there are only three of us working on the documentation so doing that could take a lot of time. I might halt incoming PRs until a format is decided then have the PRs updated to reflect it.

**Comment by devnote-dev** [comment]
Started on this now: https://github.com/devnote-dev/ptero-notes/blob/guidelines/CONTRIBUTING.md
