### ISSUE TITLE
Parameter for Wings endpoint.

### ISSUE THREAD

**Issue by DEV-DIBSTER** [devnote-dev/ptero-notes#22]
There is a new endpoint on the wings, supposedly as of [v1.10.0](https://github.com/pterodactyl/wings/releases/tag/v1.11.0).

`?v=2` Displays additional information.

**Comment by devnote-dev** [comment]
This parameter is already covered in [`GET /api/system`](https://github.com/devnote-dev/ptero-notes/blob/main/wings/system.md#get-apisystem) but there should definitely be example responses of both versions.

**Comment by DEV-DIBSTER** [comment]
@devnote-dev I'm not sure how to format the example responses, but this is what I came up with if you'd like to take a look:

https://github.com/DEV-DIBSTER/ptero-notes/blob/main/wings/system.md

**Comment by devnote-dev** [comment]
It might be worth labeling them Version 1 and Version 2, but otherwise that looks good! Feel free to send in a PR.
