### ISSUE TITLE
Remote API documentation

### ISSUE THREAD

**Issue by devnote-dev** [devnote-dev/ptero-notes#4]
Provide documentation and references for the remote API in Pterodactyl, including interactions with the Wings API.

**Comment by real2two** [comment]
I'll take on this issue. https://github.com/devnote-dev/ptero-notes/pull/15

**Comment by DEV-DIBSTER** [comment]
This issue can be closed as @real2two documented the API and his pull request was merged.

[@devnote-dev]

**Comment by devnote-dev** [comment]
Yeah, the core parts of the remote API have been documented so that's cool. At some point we may need to go back to it as there is some missing information, but that can be for another issue.
